import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { twMerge } from 'tailwind-merge'
const inter = Inter({ subsets: ['latin'] })
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: 'TweetX',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={twMerge("min-h-screen font-sans antialiased", inter.className)}>
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  )
}
